- name: Copy start stackup-bundler script for {{ network_suffix }}
  become: true
  ansible.builtin.template:
    src: start_stackup_bundler.sh.j2
    dest: "/home/ubuntu/start_bundler_{{ bundler_version }}_{{ network_suffix }}.sh"
    owner: ubuntu
    group: ubuntu
    mode: "+x"

- name: Copy stackup-bundler service for {{ network_suffix }}
  become: true
  ansible.builtin.template:
    src: stackup_bundler.service.j2
    dest: /lib/systemd/system/stackup_bundler_{{ bundler_version }}_{{ network_suffix }}.service
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Start stackup-bundler service for {{ network_suffix }}
  become: true
  ansible.builtin.systemd:
    name: stackup_bundler_{{ bundler_version }}_{{ network_suffix }}
    state: restarted
    daemon_reload: true
    enabled: true
