- name: Add ethereum repository from PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:ethereum/ethereum

- name: Update repositories cache and install ethereum package
  become: true
  ansible.builtin.apt:
    name: ethereum
    update_cache: true
