- name: Checkout github.com/maticnetwork/heimdall
  become: true
  ansible.builtin.git:
    repo: "https://github.com/maticnetwork/heimdall.git"
    dest: /home/ubuntu/heimdall
    version: "{{ heimdall_git_tag }}"
  register: checkout

- name: Build heimdall from source
  become: true
  ansible.builtin.command:
    cmd: /usr/bin/make build
    chdir: /home/ubuntu/heimdall
  when: checkout.changed
  tags:
    - skip_ansible_lint

- name: Link heimdalld binary
  become: true
  ansible.builtin.file:
    src: /home/ubuntu/heimdall/build/heimdalld
    dest: /usr/bin/heimdalld
    owner: root
    group: root
    state: link

- name: Link heimdallcli binary
  become: true
  ansible.builtin.file:
    src: /home/ubuntu/heimdall/build/heimdallcli
    dest: /usr/bin/heimdallcli
    owner: root
    group: root
    state: link
