- name: Add Go to PATH
  become: true
  ansible.builtin.lineinfile:
    dest: /home/ubuntu/.profile
    line: "export PATH=$PATH:/usr/local/go/bin"

- name: Update repositories cache and install build-essential
  become: true
  ansible.builtin.apt:
    name: build-essential
    update_cache: true

- name: Install Go from {{ go_download_src }}
  become: true
  ansible.builtin.unarchive:
    src: "{{ go_download_src }}"
    dest: /usr/local
    remote_src: true

- name: Link Go binary for Makefile commands
  become: true
  ansible.builtin.file:
    src: /usr/local/go/bin/go
    dest: /usr/bin/go
    owner: root
    group: root
    state: link
