- name: Copy start geth script for {{ network_suffix }}
  become: true
  ansible.builtin.template:
    src: start_geth.sh.j2
    dest: "/home/ubuntu/start_geth_{{ network_suffix }}.sh"
    owner: ubuntu
    group: ubuntu
    mode: "+x"

- name: Copy geth service for {{ network_suffix }}
  become: true
  ansible.builtin.template:
    src: geth.service.j2
    dest: /lib/systemd/system/geth_{{ network_suffix }}.service
    owner: ubuntu
    group: ubuntu
    mode: "0644"

- name: Start geth service for {{ network_suffix }}
  become: true
  ansible.builtin.systemd:
    name: geth_{{ network_suffix }}
    state: started
    enabled: true
